### ISSUE TITLE
BladeRF A4 Problem

### ISSUE THREAD

**Issue by damianpri** [Nuand/bladeRF-adsb#11]
where can I download the .brf file (such as http://nuand.com/fpga/adsbx40.rbf) for the A4 version?

**Comment by robertghilduta** [comment]
@damianpri the xA4 ADS-B image is available https://nuand.com/fpga/adsbxA4.rbf

**Comment by damianpri** [comment]
@robertghilduta 

edit bladeRF_adsb.c

#define FPGA_FNAME_A4 "./adsbxA4.rbf"

and edit, change

if ( fpga_size == BLADERF_FPGA_40KLE ) 
        status = bladerf_load_fpga(dev, FPGA_FNAME_40) ;

for

if ( fpga_size == BLADERF_FPGA_A4KLE ) 
        status = bladerf_load_fpga(dev, FPGA_FNAME_A4KLE) ;


run: make 

but I have the following error:
----------------------------------------------------------------------------------------------------
bladeRF_adsb.c: In function ‘main’:
bladeRF_adsb.c:219:23: error: ‘BLADERF_FPGA_A4KLE’ undeclared (first use in this function); did you mean ‘BLADERF_FPGA_40KLE’?
     if ( fpga_size == BLADERF_FPGA_A4KLE )
                       ^~~~~~~~~~~~~~~~~~
                       BLADERF_FPGA_40KLE
bladeRF_adsb.c:219:23: note: each undeclared identifier is reported only once for each function it appears in
----------------------------------------------------------------------------------------------------

any solution?

**Comment by damianpri** [comment]
I do the following:

$ git clone https://github.com/Nuand/bladeRF-adsb
$ cd bladeRF-adsb/bladeRF_adsb
$ wget http://nuand.com/fpga/adsbxA4.rbf
$ make
$ ./bladeRF_adsb



./bladeRF_adsb 
Failed to set TX VGA1 gain: Operation not supported
Couldn't configure TX module: Operation not supported

where is the problem? thanks

**Comment by kazazes** [comment]
It seems that 36d5d3107e052ee4e19a22d741b4116190f1d249 only added flashing support for the 2.0. The [tx and rx params](https://github.com/Nuand/bladeRF-adsb/blob/9a6cff472b4fe4f401bf86378342b382e30ca388/bladeRF_adsb/bladeRF_adsb.c#L145-L163) seem incompatible.

**Comment by kazazes** [comment]
More specifically, `txvga1` and `txvga2` should be `dsa`, and LNA gain should be `full` on the xA4/9.

**Comment by damianpri** [comment]
but now I have the following error:

/bladeRF_adsb$ ./bladeRF_adsb 
Failed to set samplerate = 80000: Provided parameter was out of the allowable range
Couldn't configure TX module: Provided parameter was out of the allowable range

**Comment by damianpri** [comment]
Hello
I'm still having the same problem...

./bladeRF_adsb
Failed to set TX VGA1 gain: Operation not supported
Couldn't configure TX module: Operation not supported

any suggestion of the solution in the configuration? thanks

**Comment by damianpri** [comment]
./bladeRF_adsb
[INFO @ host/libraries/libbladeRF/src/helpers/version.c:106] FPGA version (v0.10.2) is newer than entries in libbladeRF's compatibility table. Please update libbladeRF if problems arise.
Failed to set samplerate = 80000: Provided parameter was out of the allowable range
Couldn't configure TX module: Provided parameter was out of the allowable range
damian@damian-CITeA:~/SDRv2/bladeRF-adsb/bladeRF_adsb$

**Comment by mivo8311** [comment]
I have the same problem with my A4. Unsupported samplerate. Did anyone ever get their A4 working with the bladeRF-adsb?

**Comment by Nuand** [comment]
Issue should be fixed, closing.
