### ISSUE TITLE
remove binaries from git

### ISSUE THREAD

**Issue by ZeroChaos-** [Nuand/bladeRF-adsb#2]
example https://github.com/Nuand/bladeRF-adsb/blob/master/bladeRF_adsb/bladeRF_adsb
might want to add such files to gitignore so they are not accidently added. (or just build out of tree _cough_)

**Comment by bpadalino** [comment]
Removed this binary from the repository.  Other than the png in there, are there any others that should be removed?

**Comment by ZeroChaos-** [comment]
to the best of my ability that looks like the only one of note in git.  thanks!
