### ISSUE TITLE
change license so that users can...use it

### ISSUE THREAD

**Issue by ZeroChaos-** [Nuand/bladeRF-adsb#3]
" Evaluation of software may not be deployed on more than 5 devices or
last for longer than 30 working days from the time of first use of the Software."

Really?  Really? REALLY?  This kind of license will completely prevent any sane distro from packaging this.

**Comment by ZeroChaos-** [comment]
Writing your own license is extremely difficult. As evidence, several people on irc claim that bullet point 2 (quoted above) only applies to commercial users.  Of course, since it doesn't say that I disagree with that interpretation.  Moreover, the license goes on to clarify in bullet point 3 that a commerical license is available, which suggests this license doesn't cover commercial use at all.

**Comment by ZeroChaos-** [comment]
some information on licenses and distro rules:
https://www.debian.org/legal/licenses/

some information on the definition of "free" or "open" source:
https://opensource.org/osd.html
https://www.gnu.org/philosophy/free-sw.html

personally if you want to prevent commercial use I don't care at all, but the way this license is written a normal user can only use this for 30 days as an evaluation and that makes it pretty worthless for me to package.  even packaging this at all could be considered helping people to break the license since obviously it's not going to uninstall after 30 days.  again, please don't write your own license, please, please.

**Comment by ZeroChaos-** [comment]
I believe a good example of what you are trying to do is used by nmap which can be found here:
https://svn.nmap.org/nmap/COPYING

If you want to do something similar but prevent all commercial use for the "free" version you could do something similar to nmap but instead of the GPL you could use the Creative Commons Attribution-NonCommercial license which can be found in full here:
https://creativecommons.org/licenses/by-nc/4.0/legalcode
or digested for easy readying here:
https://creativecommons.org/licenses/by-nc/4.0/

**Comment by robertghilduta** [comment]
License is much more relaxed!
